### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by yairEO** [bijoythomas/sublime-mocha-test-runner#1]
I would prefer to configure the tests per-project, so when I am modifying a file in my project (I would expect the files `watch` settings to be configurable as well to control what to watch) then the tests should run automatically.

I won't remember going back to my tests file and run the tests manually, I could just do this in the terminal anyway. I want to harness the power of sublime to connect between a file-save and running tests, and showing the result in some form of icon on the bottom bar (in a very subtle way, red/green)

**Comment by bijoythomas** [comment]
Thank you for you suggestion @yairEO. 

The usage of the plugin is sort of biased towards my development style, which is very tight TDD cycles that involving switching back and forth between test and production code. I could easily focus on a single mocha unit test that I am building (without having to use _'only'_ qualifiers) and then switch to the whole _'describe'_ suite by simply having the cursor positioned properly in Sublime. 

The re-run feature comes really in handy when I have the test 'remembered' and am then building out the production code and get feedback immediately in Sublime itself.

Have you checked out https://wallabyjs.com/ for automatically running tests on file save? They have a Sublime plugin too.

**Comment by yairEO** [comment]
Yeah I know wallabyjs, it costs money :)

Thanks for sharing your side on this matter

**Comment by bijoythomas** [comment]
You could fork https://github.com/matthiasg/sublime-mocha-runner and change it so that it runs mocha without the tap output option and get pretty decent results within Sublime :-)

It seems like that plugin runs everything under test and so could potentially run any integrations tests too (if you have any) unless you configure the plugin to run tests in a specific folder under the main **test** folder.
